name: CI - Dev Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      PYTHONUNBUFFERED: 1
      POETRY_VIRTUALENVS_CREATE: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar Poetry
        run: |
          pip install poetry==1.8.4
          poetry config virtualenvs.create false

      - name: Instalar dependências com Poetry
        run: poetry install --with dev

      - name: Análise com Ruff
        run: poetry run ruff check .

      - name: Análise com MyPy
        run: poetry run mypy .

      - name: Testes com Pytest
        run: poetry run pytest

      - name: Criar tag de release candidate
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: |
          chmod +x ./infra/scripts/gerar_tag.sh
          NEW_TAG=$(./infra/scripts/gerar_tag.sh)

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/VladimirVieira/bancorn.git

          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Gerar ZIP do projeto com a tag gerada
        run: |
          if [ -n "$NEW_TAG" ]; then
            ZIP_NAME="${NEW_TAG}.zip"
            echo "Gerando arquivo: $ZIP_NAME"
            git archive --format=zip --output="$ZIP_NAME" HEAD
            echo "Arquivo $ZIP_NAME gerado com sucesso."
          else
            echo "Nenhuma tag foi gerada nesta execução. Pulando geração do ZIP."
          fi

      - name: Upload artifact do ZIP
        uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: |
            *.zip
          if-no-files-found: ignore
