name: CI - Dev Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  testes-analise:
    uses: ./.github/workflows/testes-analise.yml

  criar-tag-artefatos:
    needs: testes-analise
    uses: ./.github/workflows/tag-artefatos.yml
    if: github.event_name == 'push'
    with:
      CAMINHO_SCRIPT_TAG: ./infra/scripts/gerar_tag_rc.sh
