name: CI - Dev Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  testes-analise:
    uses: ./.github/workflows/testes-analise.yml
    with:
      python-version: '3.13'

  criar-tag-artefatos:
    needs: testes-analise
    uses: ./.github/workflows/criar-tag-artefatos.yml
    with:
      CAMINHO_SCRIPT_TAG: infra/scripts/gerar_tag_rc.sh
