name: Criar Tag e Enviar Artefatos

on:
  workflow_call:
    inputs:
      CAMINHO_SCRIPT_TAG:
        description: 'Caminho do script shell para gerar a tag'
        required: true
        type: string

jobs:
  criar-tag-e-artefatos:
    runs-on: ubuntu-latest

    env:
      PYTHONUNBUFFERED: 1
      POETRY_VIRTUALENVS_CREATE: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar nova tag
        run: |
          chmod +x ${{ inputs.CAMINHO_SCRIPT_TAG }}
          NEW_TAG=$(./${{ inputs.CAMINHO_SCRIPT_TAG }})

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/VladimirVieira/bancorn.git

          if git ls-remote --tags origin | grep -qw "refs/tags/$NEW_TAG"; then
            echo "A tag '$NEW_TAG' já existe. Ignorando criação."
          else
            git tag "$NEW_TAG"
            git push origin "$NEW_TAG"
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          fi

      - name: Criar nome para artefato (fallback)
        run: |
          if [ -z "$NEW_TAG" ]; then
            TIMESTAMP=$(date +'%Y%m%d%H%M%S')
            NEW_TAG="build-$TIMESTAMP"
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          fi

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NEW_TAG }}
          path: |
            ./*
